# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboottest?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root # 请替换为您的数据库用户名
    password: 1234 # 请替换为您的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mapper/*.xml # 如果使用XML配置，指定位置
  configuration:
    map-underscore-to-camel-case: true

  # Redis Configuration
  redis:
    host: 192.168.231.128
    port: 6379
    # password: your_redis_password # 如果您的Redis有密码，请取消注释并设置

  # Spring Cache Configuration
  cache:
    type: redis

# Server Port (Optional)
# server:
#   port: 8080

# Logging (Optional)
logging:
  level:
    com.example.t5springboot: DEBUG # 请根据您的实际包名修改